# Generated by Django 5.1 on 2024-08-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numberPlate', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingDevice',
            fields=[
                ('trackID', models.AutoField(default=100, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=False)),
                ('longitude', models.FloatField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusTrackingDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.bus')),
                ('trackID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.trackingdevice')),
            ],
        ),
    ]
