# Generated by Django 5.1 on 2024-08-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdevice',
            name='trackID',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
    ]
