# Generated by Django 5.1 on 2024-08-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_alter_trackingdevice_trackid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdevice',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdevice',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
