# Generated by Django 5.1 on 2024-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_alter_trackingdevice_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdevice',
            name='error_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
