# Generated by Django 5.1 on 2024-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_trackingdevice_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdevice',
            name='trackID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
