# Generated by Django 5.1 on 2024-09-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0005_alter_trackingdevice_trackid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdevice',
            name='bus',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_devices', to='Tracking.bus'),
            preserve_default=False,
        ),
    ]
